//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.04 at 02:42:49 PM EDT 
//


package com.dialogic.xms.msml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;group ref="{}msmlRequest" maxOccurs="unbounded"/>
 *         &lt;element name="event">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded">
 *                   &lt;sequence>
 *                     &lt;element name="name" type="{}msmlEventNameValue.datatype"/>
 *                     &lt;element name="value">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;pattern value="[a-zA-Z0-9.]+"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/choice>
 *                 &lt;attribute name="name" use="required" type="{}msmlEventName.datatype" />
 *                 &lt;attribute name="id" use="required" type="{}msmlEventSource.datatype" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="result">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="description" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="[a-zA-Z0-9.\-_]+"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                     &lt;element name="confid" type="{}confID.datatype"/>
 *                     &lt;element name="dialogid" type="{}dialogID.datatype"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *                 &lt;attribute name="response">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;pattern value="\d{3}"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="mark" type="{}mark.datatype" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *       &lt;attribute name="version" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="1.1"/>
 *             &lt;enumeration value="1.0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "msmlRequest",
    "event",
    "result"
})
@XmlRootElement(name = "msml")
public class Msml {

    @XmlElements({
        @XmlElement(name = "createconference", type = Msml.Createconference.class),
        @XmlElement(name = "modifyconference", type = Msml.Modifyconference.class),
        @XmlElement(name = "destroyconference", type = Msml.Destroyconference.class),
        @XmlElement(name = "dialogstart", type = Msml.Dialogstart.class),
        @XmlElement(name = "dialogend", type = Msml.Dialogend.class),
        @XmlElement(name = "join", type = Msml.Join.class),
        @XmlElement(name = "modifystream", type = Msml.Modifystream.class),
        @XmlElement(name = "unjoin", type = Msml.Unjoin.class),
        @XmlElement(name = "send", type = Msml.Send.class),
        @XmlElement(name = "audit", type = Msml.Audit.class)
    })
    protected List<Object> msmlRequest;
    protected Msml.Event event;
    protected Msml.Result result;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the msmlRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the msmlRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMsmlRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Msml.Createconference }
     * {@link Msml.Modifyconference }
     * {@link Msml.Destroyconference }
     * {@link Msml.Dialogstart }
     * {@link Msml.Dialogend }
     * {@link Msml.Join }
     * {@link Msml.Modifystream }
     * {@link Msml.Unjoin }
     * {@link Msml.Send }
     * {@link Msml.Audit }
     * 
     * 
     */
    public List<Object> getMsmlRequest() {
        if (msmlRequest == null) {
            msmlRequest = new ArrayList<Object>();
        }
        return this.msmlRequest;
    }

    /**
     * Gets the value of the event property.
     * 
     * @return
     *     possible object is
     *     {@link Msml.Event }
     *     
     */
    public Msml.Event getEvent() {
        return event;
    }

    /**
     * Sets the value of the event property.
     * 
     * @param value
     *     allowed object is
     *     {@link Msml.Event }
     *     
     */
    public void setEvent(Msml.Event value) {
        this.event = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link Msml.Result }
     *     
     */
    public Msml.Result getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link Msml.Result }
     *     
     */
    public void setResult(Msml.Result value) {
        this.result = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="queryid" use="required" type="{}auditQueryId.datatype" />
     *       &lt;attribute name="statelist" type="{}auditStateList.datatype" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Audit {

        @XmlAttribute(name = "queryid", required = true)
        protected String queryid;
        @XmlAttribute(name = "statelist")
        protected String statelist;

        /**
         * Gets the value of the queryid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getQueryid() {
            return queryid;
        }

        /**
         * Sets the value of the queryid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setQueryid(String value) {
            this.queryid = value;
        }

        /**
         * Gets the value of the statelist property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatelist() {
            return statelist;
        }

        /**
         * Sets the value of the statelist property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatelist(String value) {
            this.statelist = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="audiomix" type="{}audioMixType" minOccurs="0"/>
     *         &lt;element name="videolayout" type="{}videoLayoutType" minOccurs="0"/>
     *       &lt;/all>
     *       &lt;attribute name="name" type="{}msmlInstanceID.datatype" />
     *       &lt;attribute name="deletewhen" default="never">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="nomedia"/>
     *             &lt;enumeration value="nocontrol"/>
     *             &lt;enumeration value="never"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="term" type="{}boolean.datatype" default="true" />
     *       &lt;attribute ref="{}mark"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Createconference {

        protected AudioMixType audiomix;
        protected VideoLayoutType videolayout;
        @XmlAttribute(name = "name")
        protected String name;
        @XmlAttribute(name = "deletewhen")
        protected String deletewhen;
        @XmlAttribute(name = "term")
        protected BooleanDatatype term;
        @XmlAttribute(name = "mark")
        protected String mark;

        /**
         * Gets the value of the audiomix property.
         * 
         * @return
         *     possible object is
         *     {@link AudioMixType }
         *     
         */
        public AudioMixType getAudiomix() {
            return audiomix;
        }

        /**
         * Sets the value of the audiomix property.
         * 
         * @param value
         *     allowed object is
         *     {@link AudioMixType }
         *     
         */
        public void setAudiomix(AudioMixType value) {
            this.audiomix = value;
        }

        /**
         * Gets the value of the videolayout property.
         * 
         * @return
         *     possible object is
         *     {@link VideoLayoutType }
         *     
         */
        public VideoLayoutType getVideolayout() {
            return videolayout;
        }

        /**
         * Sets the value of the videolayout property.
         * 
         * @param value
         *     allowed object is
         *     {@link VideoLayoutType }
         *     
         */
        public void setVideolayout(VideoLayoutType value) {
            this.videolayout = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the deletewhen property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDeletewhen() {
            if (deletewhen == null) {
                return "never";
            } else {
                return deletewhen;
            }
        }

        /**
         * Sets the value of the deletewhen property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDeletewhen(String value) {
            this.deletewhen = value;
        }

        /**
         * Gets the value of the term property.
         * 
         * @return
         *     possible object is
         *     {@link BooleanDatatype }
         *     
         */
        public BooleanDatatype getTerm() {
            if (term == null) {
                return BooleanDatatype.TRUE;
            } else {
                return term;
            }
        }

        /**
         * Sets the value of the term property.
         * 
         * @param value
         *     allowed object is
         *     {@link BooleanDatatype }
         *     
         */
        public void setTerm(BooleanDatatype value) {
            this.term = value;
        }

        /**
         * Gets the value of the mark property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMark() {
            return mark;
        }

        /**
         * Sets the value of the mark property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMark(String value) {
            this.mark = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="audiomix" type="{}basicAudioMixType" minOccurs="0"/>
     *         &lt;element name="videolayout" type="{}basicVideoLayoutType" minOccurs="0"/>
     *       &lt;/all>
     *       &lt;attribute name="id" use="required" type="{}msmlInstanceID.datatype" />
     *       &lt;attribute ref="{}mark"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Destroyconference {

        protected BasicAudioMixType audiomix;
        protected BasicVideoLayoutType videolayout;
        @XmlAttribute(name = "id", required = true)
        protected String id;
        @XmlAttribute(name = "mark")
        protected String mark;

        /**
         * Gets the value of the audiomix property.
         * 
         * @return
         *     possible object is
         *     {@link BasicAudioMixType }
         *     
         */
        public BasicAudioMixType getAudiomix() {
            return audiomix;
        }

        /**
         * Sets the value of the audiomix property.
         * 
         * @param value
         *     allowed object is
         *     {@link BasicAudioMixType }
         *     
         */
        public void setAudiomix(BasicAudioMixType value) {
            this.audiomix = value;
        }

        /**
         * Gets the value of the videolayout property.
         * 
         * @return
         *     possible object is
         *     {@link BasicVideoLayoutType }
         *     
         */
        public BasicVideoLayoutType getVideolayout() {
            return videolayout;
        }

        /**
         * Sets the value of the videolayout property.
         * 
         * @param value
         *     allowed object is
         *     {@link BasicVideoLayoutType }
         *     
         */
        public void setVideolayout(BasicVideoLayoutType value) {
            this.videolayout = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the mark property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMark() {
            return mark;
        }

        /**
         * Sets the value of the mark property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMark(String value) {
            this.mark = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="id" use="required" type="{}dialogID.datatype" />
     *       &lt;attribute ref="{}mark"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Dialogend {

        @XmlAttribute(name = "id", required = true)
        protected String id;
        @XmlAttribute(name = "mark")
        protected String mark;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the mark property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMark() {
            return mark;
        }

        /**
         * Sets the value of the mark property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMark(String value) {
            this.mark = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;group ref="{}momlRequest" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/choice>
     *       &lt;attribute name="target" use="required" type="{}independentID.datatype" />
     *       &lt;attribute name="type" use="required" type="{}dialogLanguage.datatype" />
     *       &lt;attribute name="name" type="{}msmlInstanceID.datatype" />
     *       &lt;attribute name="src" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *       &lt;attribute ref="{}mark"/>
     *       &lt;attribute ref="{http://www.dialogic.com/DialogicTypes}target_display"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "momlRequest"
    })
    public static class Dialogstart {

        @XmlElementRefs({
            @XmlElementRef(name = "control", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "send", type = com.dialogic.xms.msml.Send.class, required = false),
            @XmlElementRef(name = "exit", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "primitive", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "disconnect", type = JAXBElement.class, required = false)
        })
        protected List<Object> momlRequest;
        @XmlAttribute(name = "target", required = true)
        protected String target;
        @XmlAttribute(name = "type", required = true)
        protected DialogLanguageDatatype type;
        @XmlAttribute(name = "name")
        protected String name;
        @XmlAttribute(name = "src")
        @XmlSchemaType(name = "anyURI")
        protected String src;
        @XmlAttribute(name = "mark")
        protected String mark;
        @XmlAttribute(name = "target_display", namespace = "http://www.dialogic.com/DialogicTypes")
        protected String targetDisplay;

        /**
         * Gets the value of the momlRequest property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the momlRequest property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMomlRequest().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link Object }{@code >}
         * {@link JAXBElement }{@code <}{@link Gain }{@code >}
         * {@link JAXBElement }{@code <}{@link Faxdetect }{@code >}
         * {@link JAXBElement }{@code <}{@link Dtmfgen }{@code >}
         * {@link JAXBElement }{@code <}{@link Collect }{@code >}
         * {@link JAXBElement }{@code <}{@link Fileop }{@code >}
         * {@link JAXBElement }{@code <}{@link Transfer }{@code >}
         * {@link JAXBElement }{@code <}{@link ExitType }{@code >}
         * {@link JAXBElement }{@code <}{@link Record }{@code >}
         * {@link JAXBElement }{@code <}{@link Dtmf }{@code >}
         * {@link com.dialogic.xms.msml.Send }
         * {@link JAXBElement }{@code <}{@link Agc }{@code >}
         * {@link JAXBElement }{@code <}{@link ExitType }{@code >}
         * {@link JAXBElement }{@code <}{@link Group }{@code >}
         * {@link JAXBElement }{@code <}{@link Play }{@code >}
         * {@link JAXBElement }{@code <}{@link PrimitiveType }{@code >}
         * 
         * 
         */
        public List<Object> getMomlRequest() {
            if (momlRequest == null) {
                momlRequest = new ArrayList<Object>();
            }
            return this.momlRequest;
        }

        /**
         * Gets the value of the target property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTarget() {
            return target;
        }

        /**
         * Sets the value of the target property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTarget(String value) {
            this.target = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link DialogLanguageDatatype }
         *     
         */
        public DialogLanguageDatatype getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link DialogLanguageDatatype }
         *     
         */
        public void setType(DialogLanguageDatatype value) {
            this.type = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the src property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSrc() {
            return src;
        }

        /**
         * Sets the value of the src property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSrc(String value) {
            this.src = value;
        }

        /**
         * Gets the value of the mark property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMark() {
            return mark;
        }

        /**
         * Sets the value of the mark property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMark(String value) {
            this.mark = value;
        }

        /**
         * Gets the value of the targetDisplay property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTargetDisplay() {
            if (targetDisplay == null) {
                return "standard";
            } else {
                return targetDisplay;
            }
        }

        /**
         * Sets the value of the targetDisplay property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTargetDisplay(String value) {
            this.targetDisplay = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded">
     *         &lt;sequence>
     *           &lt;element name="name" type="{}msmlEventNameValue.datatype"/>
     *           &lt;element name="value">
     *             &lt;simpleType>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                 &lt;pattern value="[a-zA-Z0-9.]+"/>
     *               &lt;/restriction>
     *             &lt;/simpleType>
     *           &lt;/element>
     *         &lt;/sequence>
     *       &lt;/choice>
     *       &lt;attribute name="name" use="required" type="{}msmlEventName.datatype" />
     *       &lt;attribute name="id" use="required" type="{}msmlEventSource.datatype" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nameAndValue"
    })
    public static class Event {

        @XmlElementRefs({
            @XmlElementRef(name = "name", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "value", type = JAXBElement.class, required = false)
        })
        protected List<JAXBElement<String>> nameAndValue;
        @XmlAttribute(name = "name", required = true)
        protected String name;
        @XmlAttribute(name = "id", required = true)
        protected String id;

        /**
         * Gets the value of the nameAndValue property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the nameAndValue property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNameAndValue().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * 
         * 
         */
        public List<JAXBElement<String>> getNameAndValue() {
            if (nameAndValue == null) {
                nameAndValue = new ArrayList<JAXBElement<String>>();
            }
            return this.nameAndValue;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="stream" type="{}streamType" maxOccurs="4" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="id1" use="required" type="{}independentID.datatype" />
     *       &lt;attribute name="id2" use="required" type="{}independentID.datatype" />
     *       &lt;attribute ref="{}mark"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "stream"
    })
    public static class Join {

        protected List<StreamType> stream;
        @XmlAttribute(name = "id1", required = true)
        protected String id1;
        @XmlAttribute(name = "id2", required = true)
        protected String id2;
        @XmlAttribute(name = "mark")
        protected String mark;

        /**
         * Gets the value of the stream property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the stream property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStream().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link StreamType }
         * 
         * 
         */
        public List<StreamType> getStream() {
            if (stream == null) {
                stream = new ArrayList<StreamType>();
            }
            return this.stream;
        }

        /**
         * Gets the value of the id1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId1() {
            return id1;
        }

        /**
         * Sets the value of the id1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId1(String value) {
            this.id1 = value;
        }

        /**
         * Gets the value of the id2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId2() {
            return id2;
        }

        /**
         * Sets the value of the id2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId2(String value) {
            this.id2 = value;
        }

        /**
         * Gets the value of the mark property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMark() {
            return mark;
        }

        /**
         * Sets the value of the mark property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMark(String value) {
            this.mark = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="audiomix" type="{}audioMixType" minOccurs="0"/>
     *         &lt;element name="videolayout" type="{}videoLayoutType" minOccurs="0"/>
     *       &lt;/all>
     *       &lt;attribute name="id" use="required" type="{}msmlInstanceID.datatype" />
     *       &lt;attribute ref="{}mark"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Modifyconference {

        protected AudioMixType audiomix;
        protected VideoLayoutType videolayout;
        @XmlAttribute(name = "id", required = true)
        protected String id;
        @XmlAttribute(name = "mark")
        protected String mark;

        /**
         * Gets the value of the audiomix property.
         * 
         * @return
         *     possible object is
         *     {@link AudioMixType }
         *     
         */
        public AudioMixType getAudiomix() {
            return audiomix;
        }

        /**
         * Sets the value of the audiomix property.
         * 
         * @param value
         *     allowed object is
         *     {@link AudioMixType }
         *     
         */
        public void setAudiomix(AudioMixType value) {
            this.audiomix = value;
        }

        /**
         * Gets the value of the videolayout property.
         * 
         * @return
         *     possible object is
         *     {@link VideoLayoutType }
         *     
         */
        public VideoLayoutType getVideolayout() {
            return videolayout;
        }

        /**
         * Sets the value of the videolayout property.
         * 
         * @param value
         *     allowed object is
         *     {@link VideoLayoutType }
         *     
         */
        public void setVideolayout(VideoLayoutType value) {
            this.videolayout = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the mark property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMark() {
            return mark;
        }

        /**
         * Sets the value of the mark property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMark(String value) {
            this.mark = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="stream" type="{}streamType" maxOccurs="4"/>
     *       &lt;/sequence>
     *       &lt;attribute name="id1" use="required" type="{}independentID.datatype" />
     *       &lt;attribute name="id2" use="required" type="{}independentID.datatype" />
     *       &lt;attribute name="mark" type="{}mark.datatype" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "stream"
    })
    public static class Modifystream {

        @XmlElement(required = true)
        protected List<StreamType> stream;
        @XmlAttribute(name = "id1", required = true)
        protected String id1;
        @XmlAttribute(name = "id2", required = true)
        protected String id2;
        @XmlAttribute(name = "mark")
        protected String mark;

        /**
         * Gets the value of the stream property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the stream property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStream().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link StreamType }
         * 
         * 
         */
        public List<StreamType> getStream() {
            if (stream == null) {
                stream = new ArrayList<StreamType>();
            }
            return this.stream;
        }

        /**
         * Gets the value of the id1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId1() {
            return id1;
        }

        /**
         * Sets the value of the id1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId1(String value) {
            this.id1 = value;
        }

        /**
         * Gets the value of the id2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId2() {
            return id2;
        }

        /**
         * Sets the value of the id2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId2(String value) {
            this.id2 = value;
        }

        /**
         * Gets the value of the mark property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMark() {
            return mark;
        }

        /**
         * Sets the value of the mark property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMark(String value) {
            this.mark = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="description" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="[a-zA-Z0-9.\-_]+"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;choice maxOccurs="unbounded" minOccurs="0">
     *           &lt;element name="confid" type="{}confID.datatype"/>
     *           &lt;element name="dialogid" type="{}dialogID.datatype"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *       &lt;attribute name="response">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;pattern value="\d{3}"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="mark" type="{}mark.datatype" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "description",
        "confidOrDialogid"
    })
    public static class Result {

        protected String description;
        @XmlElementRefs({
            @XmlElementRef(name = "confid", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "dialogid", type = JAXBElement.class, required = false)
        })
        protected List<JAXBElement<String>> confidOrDialogid;
        @XmlAttribute(name = "response")
        protected String response;
        @XmlAttribute(name = "mark")
        protected String mark;

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the confidOrDialogid property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the confidOrDialogid property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getConfidOrDialogid().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * 
         * 
         */
        public List<JAXBElement<String>> getConfidOrDialogid() {
            if (confidOrDialogid == null) {
                confidOrDialogid = new ArrayList<JAXBElement<String>>();
            }
            return this.confidOrDialogid;
        }

        /**
         * Gets the value of the response property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResponse() {
            return response;
        }

        /**
         * Sets the value of the response property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResponse(String value) {
            this.response = value;
        }

        /**
         * Gets the value of the mark property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMark() {
            return mark;
        }

        /**
         * Sets the value of the mark property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMark(String value) {
            this.mark = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="event" use="required" type="{}msmlEvent.datatype" />
     *       &lt;attribute name="target" use="required" type="{}msmlTarget.datatype" />
     *       &lt;attribute name="valuelist" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute ref="{}mark"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Send {

        @XmlAttribute(name = "event", required = true)
        protected String event;
        @XmlAttribute(name = "target", required = true)
        protected String target;
        @XmlAttribute(name = "valuelist")
        protected String valuelist;
        @XmlAttribute(name = "mark")
        protected String mark;

        /**
         * Gets the value of the event property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEvent() {
            return event;
        }

        /**
         * Sets the value of the event property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEvent(String value) {
            this.event = value;
        }

        /**
         * Gets the value of the target property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTarget() {
            return target;
        }

        /**
         * Sets the value of the target property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTarget(String value) {
            this.target = value;
        }

        /**
         * Gets the value of the valuelist property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValuelist() {
            return valuelist;
        }

        /**
         * Sets the value of the valuelist property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValuelist(String value) {
            this.valuelist = value;
        }

        /**
         * Gets the value of the mark property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMark() {
            return mark;
        }

        /**
         * Sets the value of the mark property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMark(String value) {
            this.mark = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="stream" type="{}basicStreamType" maxOccurs="4" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="id1" use="required" type="{}independentID.datatype" />
     *       &lt;attribute name="id2" use="required" type="{}independentID.datatype" />
     *       &lt;attribute ref="{}mark"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "stream"
    })
    public static class Unjoin {

        protected List<BasicStreamType> stream;
        @XmlAttribute(name = "id1", required = true)
        protected String id1;
        @XmlAttribute(name = "id2", required = true)
        protected String id2;
        @XmlAttribute(name = "mark")
        protected String mark;

        /**
         * Gets the value of the stream property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the stream property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStream().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BasicStreamType }
         * 
         * 
         */
        public List<BasicStreamType> getStream() {
            if (stream == null) {
                stream = new ArrayList<BasicStreamType>();
            }
            return this.stream;
        }

        /**
         * Gets the value of the id1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId1() {
            return id1;
        }

        /**
         * Sets the value of the id1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId1(String value) {
            this.id1 = value;
        }

        /**
         * Gets the value of the id2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId2() {
            return id2;
        }

        /**
         * Sets the value of the id2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId2(String value) {
            this.id2 = value;
        }

        /**
         * Gets the value of the mark property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMark() {
            return mark;
        }

        /**
         * Sets the value of the mark property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMark(String value) {
            this.mark = value;
        }

    }

}
