//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.04 at 02:42:49 PM EDT 
//


package com.dialogic.xms.msml;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}primitiveType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="audio" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                   &lt;attribute name="iterate" type="{}iterate.datatype" />
 *                   &lt;attribute name="format" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;attribute name="audiosamplerate" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                   &lt;attribute name="audiosamplesize" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="video" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                   &lt;attribute name="iterate" type="{}iterate.datatype" />
 *                   &lt;attribute name="format" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;attribute name="profile" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;attribute name="imagewidth" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                   &lt;attribute name="imageheight" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                   &lt;attribute name="maxbitrate" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                   &lt;attribute name="framerate" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="media" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;choice maxOccurs="unbounded">
 *                     &lt;element name="audio" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                             &lt;attribute name="iterate" type="{}iterate.datatype" />
 *                             &lt;attribute name="format" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                             &lt;attribute name="audiosamplerate" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                             &lt;attribute name="audiosamplesize" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="video" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                             &lt;attribute name="iterate" type="{}iterate.datatype" />
 *                             &lt;attribute name="format" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                             &lt;attribute name="profile" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                             &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                             &lt;attribute name="imagewidth" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                             &lt;attribute name="imageheight" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                             &lt;attribute name="maxbitrate" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                             &lt;attribute name="framerate" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/choice>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element ref="{}smedia" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="playexit">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;group ref="{}sendType"/>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;sequence>
 *           &lt;element name="send" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="event" use="required" type="{}momlEvent.datatype" />
 *                   &lt;attribute name="target" use="required" type="{}momlTarget.datatype" />
 *                   &lt;attribute name="namelist" type="{}momlNamelist.datatype" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="interval" type="{}posDuration.datatype" />
 *       &lt;attribute name="iterate" type="{}iterate.datatype" default="1" />
 *       &lt;attribute name="offset" type="{}duration.datatype" />
 *       &lt;attribute name="initial" default="generate">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="generate"/>
 *             &lt;enumeration value="suspend"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="maxtime" type="{}posDuration.datatype" />
 *       &lt;attribute name="skip" type="{}duration.datatype" default="3s" />
 *       &lt;attribute name="barge" type="{}boolean.datatype" default="false" />
 *       &lt;attribute name="cleardb" type="{}boolean.datatype" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "audioOrVideoOrMedia",
    "playexit",
    "send"
})
public class Play
    extends PrimitiveType
{

    @XmlElementRefs({
        @XmlElementRef(name = "audio", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "smedia", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "media", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "video", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> audioOrVideoOrMedia;
    protected Play.Playexit playexit;
    protected Play.Send send;
    @XmlAttribute(name = "interval")
    protected String interval;
    @XmlAttribute(name = "iterate")
    protected String iterate;
    @XmlAttribute(name = "offset")
    protected String offset;
    @XmlAttribute(name = "initial")
    protected String initial;
    @XmlAttribute(name = "maxtime")
    protected String maxtime;
    @XmlAttribute(name = "skip")
    protected String skip;
    @XmlAttribute(name = "barge")
    protected BooleanDatatype barge;
    @XmlAttribute(name = "cleardb")
    protected BooleanDatatype cleardb;

    /**
     * Gets the value of the audioOrVideoOrMedia property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the audioOrVideoOrMedia property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAudioOrVideoOrMedia().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Play.Audio }{@code >}
     * {@link JAXBElement }{@code <}{@link SmediaType }{@code >}
     * {@link JAXBElement }{@code <}{@link Play.Media }{@code >}
     * {@link JAXBElement }{@code <}{@link Var }{@code >}
     * {@link JAXBElement }{@code <}{@link Play.Video }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getAudioOrVideoOrMedia() {
        if (audioOrVideoOrMedia == null) {
            audioOrVideoOrMedia = new ArrayList<JAXBElement<?>>();
        }
        return this.audioOrVideoOrMedia;
    }

    /**
     * Gets the value of the playexit property.
     * 
     * @return
     *     possible object is
     *     {@link Play.Playexit }
     *     
     */
    public Play.Playexit getPlayexit() {
        return playexit;
    }

    /**
     * Sets the value of the playexit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Play.Playexit }
     *     
     */
    public void setPlayexit(Play.Playexit value) {
        this.playexit = value;
    }

    /**
     * Gets the value of the send property.
     * 
     * @return
     *     possible object is
     *     {@link Play.Send }
     *     
     */
    public Play.Send getSend() {
        return send;
    }

    /**
     * Sets the value of the send property.
     * 
     * @param value
     *     allowed object is
     *     {@link Play.Send }
     *     
     */
    public void setSend(Play.Send value) {
        this.send = value;
    }

    /**
     * Gets the value of the interval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterval() {
        return interval;
    }

    /**
     * Sets the value of the interval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterval(String value) {
        this.interval = value;
    }

    /**
     * Gets the value of the iterate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIterate() {
        if (iterate == null) {
            return "1";
        } else {
            return iterate;
        }
    }

    /**
     * Sets the value of the iterate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIterate(String value) {
        this.iterate = value;
    }

    /**
     * Gets the value of the offset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOffset() {
        return offset;
    }

    /**
     * Sets the value of the offset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOffset(String value) {
        this.offset = value;
    }

    /**
     * Gets the value of the initial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitial() {
        if (initial == null) {
            return "generate";
        } else {
            return initial;
        }
    }

    /**
     * Sets the value of the initial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitial(String value) {
        this.initial = value;
    }

    /**
     * Gets the value of the maxtime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxtime() {
        return maxtime;
    }

    /**
     * Sets the value of the maxtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxtime(String value) {
        this.maxtime = value;
    }

    /**
     * Gets the value of the skip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkip() {
        if (skip == null) {
            return "3s";
        } else {
            return skip;
        }
    }

    /**
     * Sets the value of the skip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkip(String value) {
        this.skip = value;
    }

    /**
     * Gets the value of the barge property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanDatatype }
     *     
     */
    public BooleanDatatype getBarge() {
        if (barge == null) {
            return BooleanDatatype.FALSE;
        } else {
            return barge;
        }
    }

    /**
     * Sets the value of the barge property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanDatatype }
     *     
     */
    public void setBarge(BooleanDatatype value) {
        this.barge = value;
    }

    /**
     * Gets the value of the cleardb property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanDatatype }
     *     
     */
    public BooleanDatatype getCleardb() {
        if (cleardb == null) {
            return BooleanDatatype.FALSE;
        } else {
            return cleardb;
        }
    }

    /**
     * Sets the value of the cleardb property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanDatatype }
     *     
     */
    public void setCleardb(BooleanDatatype value) {
        this.cleardb = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *       &lt;attribute name="iterate" type="{}iterate.datatype" />
     *       &lt;attribute name="format" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="audiosamplerate" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *       &lt;attribute name="audiosamplesize" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Audio {

        @XmlAttribute(name = "uri", required = true)
        @XmlSchemaType(name = "anyURI")
        protected String uri;
        @XmlAttribute(name = "iterate")
        protected String iterate;
        @XmlAttribute(name = "format")
        protected String format;
        @XmlAttribute(name = "audiosamplerate")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger audiosamplerate;
        @XmlAttribute(name = "audiosamplesize")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger audiosamplesize;

        /**
         * Gets the value of the uri property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUri() {
            return uri;
        }

        /**
         * Sets the value of the uri property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUri(String value) {
            this.uri = value;
        }

        /**
         * Gets the value of the iterate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIterate() {
            return iterate;
        }

        /**
         * Sets the value of the iterate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIterate(String value) {
            this.iterate = value;
        }

        /**
         * Gets the value of the format property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFormat() {
            return format;
        }

        /**
         * Sets the value of the format property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFormat(String value) {
            this.format = value;
        }

        /**
         * Gets the value of the audiosamplerate property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getAudiosamplerate() {
            return audiosamplerate;
        }

        /**
         * Sets the value of the audiosamplerate property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setAudiosamplerate(BigInteger value) {
            this.audiosamplerate = value;
        }

        /**
         * Gets the value of the audiosamplesize property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getAudiosamplesize() {
            return audiosamplesize;
        }

        /**
         * Sets the value of the audiosamplesize property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setAudiosamplesize(BigInteger value) {
            this.audiosamplesize = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded">
     *         &lt;element name="audio" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *                 &lt;attribute name="iterate" type="{}iterate.datatype" />
     *                 &lt;attribute name="format" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="audiosamplerate" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *                 &lt;attribute name="audiosamplesize" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="video" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *                 &lt;attribute name="iterate" type="{}iterate.datatype" />
     *                 &lt;attribute name="format" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="profile" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="imagewidth" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *                 &lt;attribute name="imageheight" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *                 &lt;attribute name="maxbitrate" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *                 &lt;attribute name="framerate" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "audioOrVideo"
    })
    public static class Media {

        @XmlElements({
            @XmlElement(name = "audio", type = Play.Media.Audio.class),
            @XmlElement(name = "video", type = Play.Media.Video.class)
        })
        protected List<Object> audioOrVideo;

        /**
         * Gets the value of the audioOrVideo property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the audioOrVideo property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAudioOrVideo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Play.Media.Audio }
         * {@link Play.Media.Video }
         * 
         * 
         */
        public List<Object> getAudioOrVideo() {
            if (audioOrVideo == null) {
                audioOrVideo = new ArrayList<Object>();
            }
            return this.audioOrVideo;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
         *       &lt;attribute name="iterate" type="{}iterate.datatype" />
         *       &lt;attribute name="format" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="audiosamplerate" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
         *       &lt;attribute name="audiosamplesize" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Audio {

            @XmlAttribute(name = "uri", required = true)
            @XmlSchemaType(name = "anyURI")
            protected String uri;
            @XmlAttribute(name = "iterate")
            protected String iterate;
            @XmlAttribute(name = "format")
            protected String format;
            @XmlAttribute(name = "audiosamplerate")
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger audiosamplerate;
            @XmlAttribute(name = "audiosamplesize")
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger audiosamplesize;

            /**
             * Gets the value of the uri property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUri() {
                return uri;
            }

            /**
             * Sets the value of the uri property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUri(String value) {
                this.uri = value;
            }

            /**
             * Gets the value of the iterate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIterate() {
                return iterate;
            }

            /**
             * Sets the value of the iterate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIterate(String value) {
                this.iterate = value;
            }

            /**
             * Gets the value of the format property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFormat() {
                return format;
            }

            /**
             * Sets the value of the format property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFormat(String value) {
                this.format = value;
            }

            /**
             * Gets the value of the audiosamplerate property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getAudiosamplerate() {
                return audiosamplerate;
            }

            /**
             * Sets the value of the audiosamplerate property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setAudiosamplerate(BigInteger value) {
                this.audiosamplerate = value;
            }

            /**
             * Gets the value of the audiosamplesize property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getAudiosamplesize() {
                return audiosamplesize;
            }

            /**
             * Sets the value of the audiosamplesize property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setAudiosamplesize(BigInteger value) {
                this.audiosamplesize = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
         *       &lt;attribute name="iterate" type="{}iterate.datatype" />
         *       &lt;attribute name="format" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="profile" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="imagewidth" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
         *       &lt;attribute name="imageheight" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
         *       &lt;attribute name="maxbitrate" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
         *       &lt;attribute name="framerate" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Video {

            @XmlAttribute(name = "uri", required = true)
            @XmlSchemaType(name = "anyURI")
            protected String uri;
            @XmlAttribute(name = "iterate")
            protected String iterate;
            @XmlAttribute(name = "format")
            protected String format;
            @XmlAttribute(name = "profile")
            protected String profile;
            @XmlAttribute(name = "level")
            protected String level;
            @XmlAttribute(name = "imagewidth")
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger imagewidth;
            @XmlAttribute(name = "imageheight")
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger imageheight;
            @XmlAttribute(name = "maxbitrate")
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger maxbitrate;
            @XmlAttribute(name = "framerate")
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger framerate;

            /**
             * Gets the value of the uri property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUri() {
                return uri;
            }

            /**
             * Sets the value of the uri property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUri(String value) {
                this.uri = value;
            }

            /**
             * Gets the value of the iterate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIterate() {
                return iterate;
            }

            /**
             * Sets the value of the iterate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIterate(String value) {
                this.iterate = value;
            }

            /**
             * Gets the value of the format property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFormat() {
                return format;
            }

            /**
             * Sets the value of the format property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFormat(String value) {
                this.format = value;
            }

            /**
             * Gets the value of the profile property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProfile() {
                return profile;
            }

            /**
             * Sets the value of the profile property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProfile(String value) {
                this.profile = value;
            }

            /**
             * Gets the value of the level property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLevel() {
                return level;
            }

            /**
             * Sets the value of the level property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLevel(String value) {
                this.level = value;
            }

            /**
             * Gets the value of the imagewidth property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getImagewidth() {
                return imagewidth;
            }

            /**
             * Sets the value of the imagewidth property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setImagewidth(BigInteger value) {
                this.imagewidth = value;
            }

            /**
             * Gets the value of the imageheight property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getImageheight() {
                return imageheight;
            }

            /**
             * Sets the value of the imageheight property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setImageheight(BigInteger value) {
                this.imageheight = value;
            }

            /**
             * Gets the value of the maxbitrate property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getMaxbitrate() {
                return maxbitrate;
            }

            /**
             * Sets the value of the maxbitrate property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setMaxbitrate(BigInteger value) {
                this.maxbitrate = value;
            }

            /**
             * Gets the value of the framerate property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getFramerate() {
                return framerate;
            }

            /**
             * Sets the value of the framerate property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setFramerate(BigInteger value) {
                this.framerate = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{}sendType"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "send",
        "exit",
        "disconnect"
    })
    public static class Playexit {

        protected List<com.dialogic.xms.msml.Send> send;
        protected ExitType exit;
        protected ExitType disconnect;

        /**
         * Gets the value of the send property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the send property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSend().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link com.dialogic.xms.msml.Send }
         * 
         * 
         */
        public List<com.dialogic.xms.msml.Send> getSend() {
            if (send == null) {
                send = new ArrayList<com.dialogic.xms.msml.Send>();
            }
            return this.send;
        }

        /**
         * Gets the value of the exit property.
         * 
         * @return
         *     possible object is
         *     {@link ExitType }
         *     
         */
        public ExitType getExit() {
            return exit;
        }

        /**
         * Sets the value of the exit property.
         * 
         * @param value
         *     allowed object is
         *     {@link ExitType }
         *     
         */
        public void setExit(ExitType value) {
            this.exit = value;
        }

        /**
         * Gets the value of the disconnect property.
         * 
         * @return
         *     possible object is
         *     {@link ExitType }
         *     
         */
        public ExitType getDisconnect() {
            return disconnect;
        }

        /**
         * Sets the value of the disconnect property.
         * 
         * @param value
         *     allowed object is
         *     {@link ExitType }
         *     
         */
        public void setDisconnect(ExitType value) {
            this.disconnect = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="event" use="required" type="{}momlEvent.datatype" />
     *       &lt;attribute name="target" use="required" type="{}momlTarget.datatype" />
     *       &lt;attribute name="namelist" type="{}momlNamelist.datatype" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Send {

        @XmlAttribute(name = "event", required = true)
        protected String event;
        @XmlAttribute(name = "target", required = true)
        protected String target;
        @XmlAttribute(name = "namelist")
        protected String namelist;

        /**
         * Gets the value of the event property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEvent() {
            return event;
        }

        /**
         * Sets the value of the event property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEvent(String value) {
            this.event = value;
        }

        /**
         * Gets the value of the target property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTarget() {
            return target;
        }

        /**
         * Sets the value of the target property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTarget(String value) {
            this.target = value;
        }

        /**
         * Gets the value of the namelist property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNamelist() {
            return namelist;
        }

        /**
         * Sets the value of the namelist property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNamelist(String value) {
            this.namelist = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *       &lt;attribute name="iterate" type="{}iterate.datatype" />
     *       &lt;attribute name="format" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="profile" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="imagewidth" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *       &lt;attribute name="imageheight" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *       &lt;attribute name="maxbitrate" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *       &lt;attribute name="framerate" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Video {

        @XmlAttribute(name = "uri", required = true)
        @XmlSchemaType(name = "anyURI")
        protected String uri;
        @XmlAttribute(name = "iterate")
        protected String iterate;
        @XmlAttribute(name = "format")
        protected String format;
        @XmlAttribute(name = "profile")
        protected String profile;
        @XmlAttribute(name = "level")
        protected String level;
        @XmlAttribute(name = "imagewidth")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger imagewidth;
        @XmlAttribute(name = "imageheight")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger imageheight;
        @XmlAttribute(name = "maxbitrate")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger maxbitrate;
        @XmlAttribute(name = "framerate")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger framerate;

        /**
         * Gets the value of the uri property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUri() {
            return uri;
        }

        /**
         * Sets the value of the uri property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUri(String value) {
            this.uri = value;
        }

        /**
         * Gets the value of the iterate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIterate() {
            return iterate;
        }

        /**
         * Sets the value of the iterate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIterate(String value) {
            this.iterate = value;
        }

        /**
         * Gets the value of the format property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFormat() {
            return format;
        }

        /**
         * Sets the value of the format property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFormat(String value) {
            this.format = value;
        }

        /**
         * Gets the value of the profile property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProfile() {
            return profile;
        }

        /**
         * Sets the value of the profile property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProfile(String value) {
            this.profile = value;
        }

        /**
         * Gets the value of the level property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLevel() {
            return level;
        }

        /**
         * Sets the value of the level property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLevel(String value) {
            this.level = value;
        }

        /**
         * Gets the value of the imagewidth property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getImagewidth() {
            return imagewidth;
        }

        /**
         * Sets the value of the imagewidth property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setImagewidth(BigInteger value) {
            this.imagewidth = value;
        }

        /**
         * Gets the value of the imageheight property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getImageheight() {
            return imageheight;
        }

        /**
         * Sets the value of the imageheight property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setImageheight(BigInteger value) {
            this.imageheight = value;
        }

        /**
         * Gets the value of the maxbitrate property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getMaxbitrate() {
            return maxbitrate;
        }

        /**
         * Sets the value of the maxbitrate property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setMaxbitrate(BigInteger value) {
            this.maxbitrate = value;
        }

        /**
         * Gets the value of the framerate property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getFramerate() {
            return framerate;
        }

        /**
         * Sets the value of the framerate property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setFramerate(BigInteger value) {
            this.framerate = value;
        }

    }

}
