//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.04 at 02:42:49 PM EDT 
//


package com.dialogic.xms.msml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}primitiveType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="fileobj" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="objid" type="{}momlID.datatype" />
 *                   &lt;attribute name="iterate" type="{}iterate.datatype" default="1" />
 *                   &lt;attribute name="retry" type="{http://www.dialogic.com/DialogicTypes}retry.datatype" default="0" />
 *                   &lt;attribute name="src" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                   &lt;attribute name="dest" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                   &lt;attribute name="wait" type="{}boolean.datatype" default="false" />
 *                   &lt;attribute name="contenttype" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;attribute name="delete" type="{}boolean.datatype" default="false" />
 *                   &lt;attribute name="overwrite" type="{}boolean.datatype" default="true" />
 *                   &lt;attribute name="append" type="{}boolean.datatype" default="false" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="messageobj" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;choice maxOccurs="unbounded">
 *                     &lt;element name="content" maxOccurs="unbounded" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;simpleContent>
 *                           &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                             &lt;attribute name="contentid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                             &lt;attribute name="contenttype" type="{http://www.w3.org/2001/XMLSchema}string" default="text/plain" />
 *                             &lt;attribute name="contentdisposition" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;/extension>
 *                         &lt;/simpleContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/choice>
 *                   &lt;attribute name="objid" type="{}momlID.datatype" />
 *                   &lt;attribute name="iterate" type="{}iterate.datatype" default="1" />
 *                   &lt;attribute name="retry" type="{http://www.dialogic.com/DialogicTypes}retry.datatype" default="0" />
 *                   &lt;attribute name="src" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                   &lt;attribute name="dest" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                   &lt;attribute name="wait" type="{}boolean.datatype" default="false" />
 *                   &lt;attribute name="contenttype" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element name="transferstart" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="transferobjstart" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="transferobjdone" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{}sendType"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="transferexit" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{}sendType"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="initial" default="transmit">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="transmit"/>
 *             &lt;enumeration value="suspend"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="iterate" type="{}iterate.datatype" default="1" />
 *       &lt;attribute name="retry" type="{http://www.dialogic.com/DialogicTypes}retry.datatype" default="0" />
 *       &lt;attribute name="starttimer" type="{}boolean.datatype" default="false" />
 *       &lt;attribute name="ftt" type="{}posDuration.datatype" />
 *       &lt;attribute name="itt" type="{}posDuration.datatype" />
 *       &lt;attribute name="maxtime" type="{}posDuration.datatype" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fileobjOrMessageobj",
    "transferstart",
    "transferobjstart",
    "transferobjdone",
    "transferexit"
})
public class Transfer
    extends PrimitiveType
{

    @XmlElements({
        @XmlElement(name = "fileobj", type = Transfer.Fileobj.class),
        @XmlElement(name = "messageobj", type = Transfer.Messageobj.class)
    })
    protected List<Object> fileobjOrMessageobj;
    protected Object transferstart;
    protected Object transferobjstart;
    protected Transfer.Transferobjdone transferobjdone;
    protected Transfer.Transferexit transferexit;
    @XmlAttribute(name = "initial")
    protected String initial;
    @XmlAttribute(name = "iterate")
    protected String iterate;
    @XmlAttribute(name = "retry")
    protected String retry;
    @XmlAttribute(name = "starttimer")
    protected BooleanDatatype starttimer;
    @XmlAttribute(name = "ftt")
    protected String ftt;
    @XmlAttribute(name = "itt")
    protected String itt;
    @XmlAttribute(name = "maxtime")
    protected String maxtime;

    /**
     * Gets the value of the fileobjOrMessageobj property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fileobjOrMessageobj property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFileobjOrMessageobj().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Transfer.Fileobj }
     * {@link Transfer.Messageobj }
     * 
     * 
     */
    public List<Object> getFileobjOrMessageobj() {
        if (fileobjOrMessageobj == null) {
            fileobjOrMessageobj = new ArrayList<Object>();
        }
        return this.fileobjOrMessageobj;
    }

    /**
     * Gets the value of the transferstart property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTransferstart() {
        return transferstart;
    }

    /**
     * Sets the value of the transferstart property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTransferstart(Object value) {
        this.transferstart = value;
    }

    /**
     * Gets the value of the transferobjstart property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTransferobjstart() {
        return transferobjstart;
    }

    /**
     * Sets the value of the transferobjstart property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTransferobjstart(Object value) {
        this.transferobjstart = value;
    }

    /**
     * Gets the value of the transferobjdone property.
     * 
     * @return
     *     possible object is
     *     {@link Transfer.Transferobjdone }
     *     
     */
    public Transfer.Transferobjdone getTransferobjdone() {
        return transferobjdone;
    }

    /**
     * Sets the value of the transferobjdone property.
     * 
     * @param value
     *     allowed object is
     *     {@link Transfer.Transferobjdone }
     *     
     */
    public void setTransferobjdone(Transfer.Transferobjdone value) {
        this.transferobjdone = value;
    }

    /**
     * Gets the value of the transferexit property.
     * 
     * @return
     *     possible object is
     *     {@link Transfer.Transferexit }
     *     
     */
    public Transfer.Transferexit getTransferexit() {
        return transferexit;
    }

    /**
     * Sets the value of the transferexit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Transfer.Transferexit }
     *     
     */
    public void setTransferexit(Transfer.Transferexit value) {
        this.transferexit = value;
    }

    /**
     * Gets the value of the initial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitial() {
        if (initial == null) {
            return "transmit";
        } else {
            return initial;
        }
    }

    /**
     * Sets the value of the initial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitial(String value) {
        this.initial = value;
    }

    /**
     * Gets the value of the iterate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIterate() {
        if (iterate == null) {
            return "1";
        } else {
            return iterate;
        }
    }

    /**
     * Sets the value of the iterate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIterate(String value) {
        this.iterate = value;
    }

    /**
     * Gets the value of the retry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetry() {
        if (retry == null) {
            return "0";
        } else {
            return retry;
        }
    }

    /**
     * Sets the value of the retry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetry(String value) {
        this.retry = value;
    }

    /**
     * Gets the value of the starttimer property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanDatatype }
     *     
     */
    public BooleanDatatype getStarttimer() {
        if (starttimer == null) {
            return BooleanDatatype.FALSE;
        } else {
            return starttimer;
        }
    }

    /**
     * Sets the value of the starttimer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanDatatype }
     *     
     */
    public void setStarttimer(BooleanDatatype value) {
        this.starttimer = value;
    }

    /**
     * Gets the value of the ftt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFtt() {
        return ftt;
    }

    /**
     * Sets the value of the ftt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFtt(String value) {
        this.ftt = value;
    }

    /**
     * Gets the value of the itt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItt() {
        return itt;
    }

    /**
     * Sets the value of the itt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItt(String value) {
        this.itt = value;
    }

    /**
     * Gets the value of the maxtime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxtime() {
        return maxtime;
    }

    /**
     * Sets the value of the maxtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxtime(String value) {
        this.maxtime = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="objid" type="{}momlID.datatype" />
     *       &lt;attribute name="iterate" type="{}iterate.datatype" default="1" />
     *       &lt;attribute name="retry" type="{http://www.dialogic.com/DialogicTypes}retry.datatype" default="0" />
     *       &lt;attribute name="src" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *       &lt;attribute name="dest" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *       &lt;attribute name="wait" type="{}boolean.datatype" default="false" />
     *       &lt;attribute name="contenttype" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="delete" type="{}boolean.datatype" default="false" />
     *       &lt;attribute name="overwrite" type="{}boolean.datatype" default="true" />
     *       &lt;attribute name="append" type="{}boolean.datatype" default="false" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Fileobj {

        @XmlAttribute(name = "objid")
        protected String objid;
        @XmlAttribute(name = "iterate")
        protected String iterate;
        @XmlAttribute(name = "retry")
        protected String retry;
        @XmlAttribute(name = "src", required = true)
        @XmlSchemaType(name = "anyURI")
        protected String src;
        @XmlAttribute(name = "dest")
        @XmlSchemaType(name = "anyURI")
        protected String dest;
        @XmlAttribute(name = "wait")
        protected BooleanDatatype wait;
        @XmlAttribute(name = "contenttype")
        protected String contenttype;
        @XmlAttribute(name = "delete")
        protected BooleanDatatype delete;
        @XmlAttribute(name = "overwrite")
        protected BooleanDatatype overwrite;
        @XmlAttribute(name = "append")
        protected BooleanDatatype append;

        /**
         * Gets the value of the objid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getObjid() {
            return objid;
        }

        /**
         * Sets the value of the objid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setObjid(String value) {
            this.objid = value;
        }

        /**
         * Gets the value of the iterate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIterate() {
            if (iterate == null) {
                return "1";
            } else {
                return iterate;
            }
        }

        /**
         * Sets the value of the iterate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIterate(String value) {
            this.iterate = value;
        }

        /**
         * Gets the value of the retry property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRetry() {
            if (retry == null) {
                return "0";
            } else {
                return retry;
            }
        }

        /**
         * Sets the value of the retry property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRetry(String value) {
            this.retry = value;
        }

        /**
         * Gets the value of the src property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSrc() {
            return src;
        }

        /**
         * Sets the value of the src property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSrc(String value) {
            this.src = value;
        }

        /**
         * Gets the value of the dest property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDest() {
            return dest;
        }

        /**
         * Sets the value of the dest property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDest(String value) {
            this.dest = value;
        }

        /**
         * Gets the value of the wait property.
         * 
         * @return
         *     possible object is
         *     {@link BooleanDatatype }
         *     
         */
        public BooleanDatatype getWait() {
            if (wait == null) {
                return BooleanDatatype.FALSE;
            } else {
                return wait;
            }
        }

        /**
         * Sets the value of the wait property.
         * 
         * @param value
         *     allowed object is
         *     {@link BooleanDatatype }
         *     
         */
        public void setWait(BooleanDatatype value) {
            this.wait = value;
        }

        /**
         * Gets the value of the contenttype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContenttype() {
            return contenttype;
        }

        /**
         * Sets the value of the contenttype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContenttype(String value) {
            this.contenttype = value;
        }

        /**
         * Gets the value of the delete property.
         * 
         * @return
         *     possible object is
         *     {@link BooleanDatatype }
         *     
         */
        public BooleanDatatype getDelete() {
            if (delete == null) {
                return BooleanDatatype.FALSE;
            } else {
                return delete;
            }
        }

        /**
         * Sets the value of the delete property.
         * 
         * @param value
         *     allowed object is
         *     {@link BooleanDatatype }
         *     
         */
        public void setDelete(BooleanDatatype value) {
            this.delete = value;
        }

        /**
         * Gets the value of the overwrite property.
         * 
         * @return
         *     possible object is
         *     {@link BooleanDatatype }
         *     
         */
        public BooleanDatatype getOverwrite() {
            if (overwrite == null) {
                return BooleanDatatype.TRUE;
            } else {
                return overwrite;
            }
        }

        /**
         * Sets the value of the overwrite property.
         * 
         * @param value
         *     allowed object is
         *     {@link BooleanDatatype }
         *     
         */
        public void setOverwrite(BooleanDatatype value) {
            this.overwrite = value;
        }

        /**
         * Gets the value of the append property.
         * 
         * @return
         *     possible object is
         *     {@link BooleanDatatype }
         *     
         */
        public BooleanDatatype getAppend() {
            if (append == null) {
                return BooleanDatatype.FALSE;
            } else {
                return append;
            }
        }

        /**
         * Sets the value of the append property.
         * 
         * @param value
         *     allowed object is
         *     {@link BooleanDatatype }
         *     
         */
        public void setAppend(BooleanDatatype value) {
            this.append = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded">
     *         &lt;element name="content" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="contentid" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="contenttype" type="{http://www.w3.org/2001/XMLSchema}string" default="text/plain" />
     *                 &lt;attribute name="contentdisposition" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *       &lt;attribute name="objid" type="{}momlID.datatype" />
     *       &lt;attribute name="iterate" type="{}iterate.datatype" default="1" />
     *       &lt;attribute name="retry" type="{http://www.dialogic.com/DialogicTypes}retry.datatype" default="0" />
     *       &lt;attribute name="src" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *       &lt;attribute name="dest" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *       &lt;attribute name="wait" type="{}boolean.datatype" default="false" />
     *       &lt;attribute name="contenttype" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class Messageobj {

        protected List<Transfer.Messageobj.Content> content;
        @XmlAttribute(name = "objid")
        protected String objid;
        @XmlAttribute(name = "iterate")
        protected String iterate;
        @XmlAttribute(name = "retry")
        protected String retry;
        @XmlAttribute(name = "src", required = true)
        @XmlSchemaType(name = "anyURI")
        protected String src;
        @XmlAttribute(name = "dest")
        @XmlSchemaType(name = "anyURI")
        protected String dest;
        @XmlAttribute(name = "wait")
        protected BooleanDatatype wait;
        @XmlAttribute(name = "contenttype")
        protected String contenttype;

        /**
         * Gets the value of the content property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the content property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Transfer.Messageobj.Content }
         * 
         * 
         */
        public List<Transfer.Messageobj.Content> getContent() {
            if (content == null) {
                content = new ArrayList<Transfer.Messageobj.Content>();
            }
            return this.content;
        }

        /**
         * Gets the value of the objid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getObjid() {
            return objid;
        }

        /**
         * Sets the value of the objid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setObjid(String value) {
            this.objid = value;
        }

        /**
         * Gets the value of the iterate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIterate() {
            if (iterate == null) {
                return "1";
            } else {
                return iterate;
            }
        }

        /**
         * Sets the value of the iterate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIterate(String value) {
            this.iterate = value;
        }

        /**
         * Gets the value of the retry property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRetry() {
            if (retry == null) {
                return "0";
            } else {
                return retry;
            }
        }

        /**
         * Sets the value of the retry property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRetry(String value) {
            this.retry = value;
        }

        /**
         * Gets the value of the src property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSrc() {
            return src;
        }

        /**
         * Sets the value of the src property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSrc(String value) {
            this.src = value;
        }

        /**
         * Gets the value of the dest property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDest() {
            return dest;
        }

        /**
         * Sets the value of the dest property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDest(String value) {
            this.dest = value;
        }

        /**
         * Gets the value of the wait property.
         * 
         * @return
         *     possible object is
         *     {@link BooleanDatatype }
         *     
         */
        public BooleanDatatype getWait() {
            if (wait == null) {
                return BooleanDatatype.FALSE;
            } else {
                return wait;
            }
        }

        /**
         * Sets the value of the wait property.
         * 
         * @param value
         *     allowed object is
         *     {@link BooleanDatatype }
         *     
         */
        public void setWait(BooleanDatatype value) {
            this.wait = value;
        }

        /**
         * Gets the value of the contenttype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContenttype() {
            return contenttype;
        }

        /**
         * Sets the value of the contenttype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContenttype(String value) {
            this.contenttype = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="contentid" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="contenttype" type="{http://www.w3.org/2001/XMLSchema}string" default="text/plain" />
         *       &lt;attribute name="contentdisposition" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Content {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "contentid")
            protected String contentid;
            @XmlAttribute(name = "contenttype")
            protected String contenttype;
            @XmlAttribute(name = "contentdisposition")
            protected String contentdisposition;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the contentid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContentid() {
                return contentid;
            }

            /**
             * Sets the value of the contentid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContentid(String value) {
                this.contentid = value;
            }

            /**
             * Gets the value of the contenttype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContenttype() {
                if (contenttype == null) {
                    return "text/plain";
                } else {
                    return contenttype;
                }
            }

            /**
             * Sets the value of the contenttype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContenttype(String value) {
                this.contenttype = value;
            }

            /**
             * Gets the value of the contentdisposition property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContentdisposition() {
                return contentdisposition;
            }

            /**
             * Sets the value of the contentdisposition property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContentdisposition(String value) {
                this.contentdisposition = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{}sendType"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "send",
        "exit",
        "disconnect"
    })
    public static class Transferexit {

        protected List<Send> send;
        protected ExitType exit;
        protected ExitType disconnect;

        /**
         * Gets the value of the send property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the send property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSend().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Send }
         * 
         * 
         */
        public List<Send> getSend() {
            if (send == null) {
                send = new ArrayList<Send>();
            }
            return this.send;
        }

        /**
         * Gets the value of the exit property.
         * 
         * @return
         *     possible object is
         *     {@link ExitType }
         *     
         */
        public ExitType getExit() {
            return exit;
        }

        /**
         * Sets the value of the exit property.
         * 
         * @param value
         *     allowed object is
         *     {@link ExitType }
         *     
         */
        public void setExit(ExitType value) {
            this.exit = value;
        }

        /**
         * Gets the value of the disconnect property.
         * 
         * @return
         *     possible object is
         *     {@link ExitType }
         *     
         */
        public ExitType getDisconnect() {
            return disconnect;
        }

        /**
         * Sets the value of the disconnect property.
         * 
         * @param value
         *     allowed object is
         *     {@link ExitType }
         *     
         */
        public void setDisconnect(ExitType value) {
            this.disconnect = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{}sendType"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "send",
        "exit",
        "disconnect"
    })
    public static class Transferobjdone {

        protected List<Send> send;
        protected ExitType exit;
        protected ExitType disconnect;

        /**
         * Gets the value of the send property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the send property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSend().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Send }
         * 
         * 
         */
        public List<Send> getSend() {
            if (send == null) {
                send = new ArrayList<Send>();
            }
            return this.send;
        }

        /**
         * Gets the value of the exit property.
         * 
         * @return
         *     possible object is
         *     {@link ExitType }
         *     
         */
        public ExitType getExit() {
            return exit;
        }

        /**
         * Sets the value of the exit property.
         * 
         * @param value
         *     allowed object is
         *     {@link ExitType }
         *     
         */
        public void setExit(ExitType value) {
            this.exit = value;
        }

        /**
         * Gets the value of the disconnect property.
         * 
         * @return
         *     possible object is
         *     {@link ExitType }
         *     
         */
        public ExitType getDisconnect() {
            return disconnect;
        }

        /**
         * Sets the value of the disconnect property.
         * 
         * @param value
         *     allowed object is
         *     {@link ExitType }
         *     
         */
        public void setDisconnect(ExitType value) {
            this.disconnect = value;
        }

    }

}
