//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.04 at 02:42:49 PM EDT 
//


package com.dialogic.xms.msml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for videoLayoutType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="videoLayoutType">
 *   &lt;complexContent>
 *     &lt;extension base="{}basicVideoLayoutType">
 *       &lt;sequence>
 *         &lt;element name="root" type="{}rootType" minOccurs="0"/>
 *         &lt;element name="selector" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{}selectorType">
 *                 &lt;choice>
 *                   &lt;element name="root" type="{}rootType" minOccurs="0"/>
 *                   &lt;element name="region" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="left" type="{}regionPosition.datatype" />
 *                           &lt;attribute name="top" type="{}regionPosition.datatype" />
 *                           &lt;attribute name="relativesize">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="1/4"/>
 *                                 &lt;enumeration value="1/3"/>
 *                                 &lt;enumeration value="1/2"/>
 *                                 &lt;enumeration value="2/3"/>
 *                                 &lt;enumeration value="3/4"/>
 *                                 &lt;enumeration value="1"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="priority">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *                                 &lt;minInclusive value="0"/>
 *                                 &lt;maxExclusive value="1"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="region" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{}regionType">
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "videoLayoutType", propOrder = {
    "root",
    "selector",
    "region"
})
public class VideoLayoutType
    extends BasicVideoLayoutType
{

    protected RootType root;
    protected VideoLayoutType.Selector selector;
    protected List<VideoLayoutType.Region> region;

    /**
     * Gets the value of the root property.
     * 
     * @return
     *     possible object is
     *     {@link RootType }
     *     
     */
    public RootType getRoot() {
        return root;
    }

    /**
     * Sets the value of the root property.
     * 
     * @param value
     *     allowed object is
     *     {@link RootType }
     *     
     */
    public void setRoot(RootType value) {
        this.root = value;
    }

    /**
     * Gets the value of the selector property.
     * 
     * @return
     *     possible object is
     *     {@link VideoLayoutType.Selector }
     *     
     */
    public VideoLayoutType.Selector getSelector() {
        return selector;
    }

    /**
     * Sets the value of the selector property.
     * 
     * @param value
     *     allowed object is
     *     {@link VideoLayoutType.Selector }
     *     
     */
    public void setSelector(VideoLayoutType.Selector value) {
        this.selector = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the region property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VideoLayoutType.Region }
     * 
     * 
     */
    public List<VideoLayoutType.Region> getRegion() {
        if (region == null) {
            region = new ArrayList<VideoLayoutType.Region>();
        }
        return this.region;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}regionType">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Region
        extends RegionType
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}selectorType">
     *       &lt;choice>
     *         &lt;element name="root" type="{}rootType" minOccurs="0"/>
     *         &lt;element name="region" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="left" type="{}regionPosition.datatype" />
     *                 &lt;attribute name="top" type="{}regionPosition.datatype" />
     *                 &lt;attribute name="relativesize">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="1/4"/>
     *                       &lt;enumeration value="1/3"/>
     *                       &lt;enumeration value="1/2"/>
     *                       &lt;enumeration value="2/3"/>
     *                       &lt;enumeration value="3/4"/>
     *                       &lt;enumeration value="1"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="priority">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
     *                       &lt;minInclusive value="0"/>
     *                       &lt;maxExclusive value="1"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "root",
        "region"
    })
    public static class Selector
        extends SelectorType
    {

        protected RootType root;
        protected VideoLayoutType.Selector.Region region;

        /**
         * Gets the value of the root property.
         * 
         * @return
         *     possible object is
         *     {@link RootType }
         *     
         */
        public RootType getRoot() {
            return root;
        }

        /**
         * Sets the value of the root property.
         * 
         * @param value
         *     allowed object is
         *     {@link RootType }
         *     
         */
        public void setRoot(RootType value) {
            this.root = value;
        }

        /**
         * Gets the value of the region property.
         * 
         * @return
         *     possible object is
         *     {@link VideoLayoutType.Selector.Region }
         *     
         */
        public VideoLayoutType.Selector.Region getRegion() {
            return region;
        }

        /**
         * Sets the value of the region property.
         * 
         * @param value
         *     allowed object is
         *     {@link VideoLayoutType.Selector.Region }
         *     
         */
        public void setRegion(VideoLayoutType.Selector.Region value) {
            this.region = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="left" type="{}regionPosition.datatype" />
         *       &lt;attribute name="top" type="{}regionPosition.datatype" />
         *       &lt;attribute name="relativesize">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="1/4"/>
         *             &lt;enumeration value="1/3"/>
         *             &lt;enumeration value="1/2"/>
         *             &lt;enumeration value="2/3"/>
         *             &lt;enumeration value="3/4"/>
         *             &lt;enumeration value="1"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="priority">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
         *             &lt;minInclusive value="0"/>
         *             &lt;maxExclusive value="1"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Region {

            @XmlAttribute(name = "id", required = true)
            protected String id;
            @XmlAttribute(name = "left")
            protected String left;
            @XmlAttribute(name = "top")
            protected String top;
            @XmlAttribute(name = "relativesize")
            protected String relativesize;
            @XmlAttribute(name = "priority")
            protected Float priority;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the left property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLeft() {
                return left;
            }

            /**
             * Sets the value of the left property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLeft(String value) {
                this.left = value;
            }

            /**
             * Gets the value of the top property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTop() {
                return top;
            }

            /**
             * Sets the value of the top property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTop(String value) {
                this.top = value;
            }

            /**
             * Gets the value of the relativesize property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRelativesize() {
                return relativesize;
            }

            /**
             * Sets the value of the relativesize property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRelativesize(String value) {
                this.relativesize = value;
            }

            /**
             * Gets the value of the priority property.
             * 
             * @return
             *     possible object is
             *     {@link Float }
             *     
             */
            public Float getPriority() {
                return priority;
            }

            /**
             * Sets the value of the priority property.
             * 
             * @param value
             *     allowed object is
             *     {@link Float }
             *     
             */
            public void setPriority(Float value) {
                this.priority = value;
            }

        }

    }

}
